import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { Shift, Payout } from '../types'
import { calcHoursWorked, calcShiftPay, calcOutstanding } from './calculations'
import { formatDisplayDate } from './dateHelpers'

export function generatePdf(
  shifts: Shift[],
  payouts: Payout[],
  from: string,
  to: string,
  symbol: string,
  currency: string,
  currentRate: number,
): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const margin = 14
  let y = margin

  doc.setFontSize(18).setFont('helvetica', 'bold')
  doc.text('SHIFTLOG', margin, y)
  doc.setFontSize(9).setFont('helvetica', 'normal').setTextColor(150)
  doc.text('Work & Salary Report', margin, y + 5)
  doc.setTextColor(0)
  doc.setFontSize(10).setFont('helvetica', 'bold')
  doc.text(`${formatDisplayDate(from)} – ${formatDisplayDate(to)}`, 196 - margin, y, { align: 'right' })
  doc.setFontSize(8).setFont('helvetica', 'normal').setTextColor(150)
  doc.text(`Generated: ${formatDisplayDate(new Date().toISOString().slice(0, 10))}`, 196 - margin, y + 5, { align: 'right' })
  doc.setTextColor(0)
  y += 14

  doc.setDrawColor(0).setLineWidth(0.5).line(margin, y, 196 - margin, y)
  y += 6

  const totalEarned = shifts.reduce((s, sh) => s + calcShiftPay(sh.startTime, sh.endTime, sh.hourlyRateSnapshot), 0)
  const totalPaid = payouts.reduce((s, p) => s + p.amount, 0)
  const outstanding = calcOutstanding(totalEarned, totalPaid)

  const colW = (196 - margin * 2) / 3
  const summaries = [
    { label: 'Total Earned', value: `${symbol}${totalEarned.toFixed(2)}`, sub: `${shifts.length} shifts`, highlight: false },
    { label: 'Paid Out', value: `${symbol}${totalPaid.toFixed(2)}`, sub: `${payouts.length} payment(s)`, highlight: false },
    { label: 'Outstanding', value: `${symbol}${outstanding.toFixed(2)}`, sub: 'unpaid', highlight: true },
  ]
  summaries.forEach((s, i) => {
    const x = margin + i * colW
    doc.setDrawColor(s.highlight ? 220 : 200)
    doc.roundedRect(x, y, colW - 2, 18, 2, 2)
    doc.setFontSize(7).setTextColor(150).text(s.label.toUpperCase(), x + 3, y + 5)
    doc.setFontSize(12).setFont('helvetica', 'bold')
    if (s.highlight) {
      doc.setTextColor(220, 38, 38)
    } else {
      doc.setTextColor(0, 0, 0)
    }
    doc.text(s.value, x + 3, y + 12)
    doc.setFontSize(7).setFont('helvetica', 'normal').setTextColor(150)
    doc.text(s.sub, x + 3, y + 17)
  })
  doc.setTextColor(0)
  y += 24

  doc.setFontSize(8).setTextColor(100)
  doc.text(`Hourly rate: ${symbol}${currentRate.toFixed(2)}/hr  ·  Currency: ${currency}`, margin, y)
  doc.setTextColor(0)
  y += 8

  autoTable(doc, {
    startY: y,
    head: [['Date', 'Label', 'Start', 'End', 'Hours', 'Pay']],
    body: shifts.map(s => [
      formatDisplayDate(s.date),
      s.label || '—',
      s.startTime,
      s.endTime,
      `${calcHoursWorked(s.startTime, s.endTime).toFixed(2)}h`,
      `${symbol}${calcShiftPay(s.startTime, s.endTime, s.hourlyRateSnapshot).toFixed(2)}`,
    ]),
    foot: [['Total', '', '', '',
      `${shifts.reduce((s, sh) => s + calcHoursWorked(sh.startTime, sh.endTime), 0).toFixed(2)}h`,
      `${symbol}${totalEarned.toFixed(2)}`,
    ]],
    styles: { fontSize: 8 },
    headStyles: { fillColor: [20, 20, 20], textColor: [200, 200, 200] },
    footStyles: { fillColor: [240, 240, 240], fontStyle: 'bold' },
    margin: { left: margin, right: margin },
  })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 8

  if (payouts.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [['Date', 'Notes', 'Amount']],
      body: payouts.map(p => [formatDisplayDate(p.date), p.notes || '—', `${symbol}${p.amount.toFixed(2)}`]),
      foot: [['Total Paid', '', `${symbol}${totalPaid.toFixed(2)}`]],
      styles: { fontSize: 8 },
      headStyles: { fillColor: [20, 20, 20], textColor: [200, 200, 200] },
      footStyles: { fillColor: [240, 240, 240], fontStyle: 'bold' },
      margin: { left: margin, right: margin },
    })
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 8
  }

  doc.setDrawColor(220, 38, 38).setFillColor(255, 248, 248)
  doc.roundedRect(margin, y, 196 - margin * 2, 14, 2, 2, 'FD')
  doc.setFontSize(9).setFont('helvetica', 'bold').setTextColor(220, 38, 38)
  doc.text('Outstanding Balance', margin + 4, y + 9)
  doc.setFontSize(13)
  doc.text(`${symbol}${outstanding.toFixed(2)}`, 196 - margin - 4, y + 9, { align: 'right' })

  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(7).setTextColor(180).setFont('helvetica', 'normal')
    doc.text('Generated by ShiftLog', margin, 287)
    doc.text(`Page ${i} of ${pageCount}`, 196 - margin, 287, { align: 'right' })
  }

  doc.save(`ShiftLog-${from}-to-${to}.pdf`)
}
